// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package PostgresDB

import (
	"time"
)

type Consumer struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type Event struct {
	ID         int32     `json:"id"`
	EventName  string    `json:"event_name"`
	EventDate  time.Time `json:"event_date"`
	TotalSeats int32     `json:"total_seats"`
}

type Seat struct {
	ID         int32   `json:"id"`
	Section    string  `json:"section"`
	SeatNumber int32   `json:"seat_number"`
	SeatStatus bool    `json:"seat_status"`
	Price      float64 `json:"price"`
	EventID    int32   `json:"event_id"`
}

type Ticket struct {
	ID           int32     `json:"id"`
	ConsumerID   int32     `json:"consumer_id"`
	EventID      int32     `json:"event_id"`
	SeatID       int32     `json:"seat_id"`
	OrderTradeNo string    `json:"order_trade_no"`
	PurchaseDate time.Time `json:"purchase_date"`
	TicketStatus int32     `json:"ticket_status"`
}
