// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package PostgresDB

import (
	"context"
)

type Querier interface {
	CreateConsumer(ctx context.Context, arg CreateConsumerParams) (Consumer, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Ticket, error)
	CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error)
	DeleteTicketsByOrderTradeNo(ctx context.Context, orderTradeNo string) error
	SelectSeat(ctx context.Context, id int32) (Seat, error)
	SelectSeatsList(ctx context.Context, eventID int32) ([]Seat, error)
	SelectSeatsListByEventAndSection(ctx context.Context, arg SelectSeatsListByEventAndSectionParams) ([]Seat, error)
	// -- name: UpdateTicketStatus :many
	// UPDATE tickets SET ticket_status = $2
	// WHERE order_trade_no = $1 RETURNING *;
	SelectSectionsAndPricesByEventID(ctx context.Context, eventID int32) ([]SelectSectionsAndPricesByEventIDRow, error)
	SelectTicketListByOrderTradeNo(ctx context.Context, orderTradeNo string) ([]Ticket, error)
	UpdateSeatStatus(ctx context.Context, arg UpdateSeatStatusParams) (Seat, error)
	UpdateSeatStatusByOrderTradeNo(ctx context.Context, arg UpdateSeatStatusByOrderTradeNoParams) ([]Seat, error)
	UpdateSeatStatusBySeatIDs(ctx context.Context, arg UpdateSeatStatusBySeatIDsParams) error
	UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) ([]UpdateTicketStatusRow, error)
}

var _ Querier = (*Queries)(nil)
