// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: seats_repository.sql

package PostgresDB

import (
	"context"
)

const selectSeatsList = `-- name: SelectSeatsList :many
SELECT id, section, seat_number, seat_status, price, event_id FROM seats WhERE event_id = $1
`

func (q *Queries) SelectSeatsList(ctx context.Context, eventID int32) ([]Seat, error) {
	rows, err := q.db.QueryContext(ctx, selectSeatsList, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seat{}
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.SeatNumber,
			&i.SeatStatus,
			&i.Price,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
